AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a cross-account IAM role for Tailpipe to access CloudWatch metrics data.

Resources:
  TailpipeCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: tailpipe-child-connector
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::336268260260:role/TailpipeConnector-Prod"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: tailpipe_child_connector_policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:GetMetricStatistics"
                Resource: "*"